# Generated by Django 2.2.3 on 2020-04-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallary',
        ),
    ]
